#!/bin/bash

ARGS=( ${*} )
readonly SR_USER="${ARGS[0]}"
readonly USER="$(printf '%s' "${ARGS[1]}"|base64 -D -)"
TEXT="$(printf '%s' "${ARGS[2]}"|base64 -D -)"

# Shadowrun date!
[ $((${RANDOM}%20)) -eq 0 ] && SR_DATE="$(awk -F -v USER="${SR_USER}" '$1==USER {print $2}' online_progs/sr_date)" || SR_DATE=''

case ${SR_DATE} in
'') 
	[ "${TEXT}" != "${TEXT%###}" ] && { SR_DATE="$(awk -F -v USER="${SR_USER}" '$1==USER {print $2}' online_progs/sr_date)" && TEXT="${TEXT%###}"; } || readonly SR_DATE="$(date -j -v+59y -v+2H +'< %H:%M:%S / %m-%d-%C%y >')"
esac

printf '­>>>>>[ %s ]<<<<<\n— %s %s' "${TEXT}" "${USER}" "${SR_DATE}"
